version: "3.8"
services:
  frontend:
    build:
      context: ./my-frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    # networks:
    #   - my_network

  backend:
    build:
      context: ./my-backend
      dockerfile: Dockerfile.backend
    ports:
      - "3005:3005"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: mydatabase
    # networks:
    #   - my_network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
    # networks:
    #   - my_network

